### ISSUE TITLE
Chapter 4 recipe 2 throws error

### ISSUE THREAD

**Issue by dnck** [PacktPublishing/Python-Network-Programming-Cookbook-Second-Edition#3]
The program, ```4_2_simple_http_server.py``` throws an error in Python 3.6.5. 

Here's the full traceback:
```
Custom HTTP server started on port: 8800
127.0.0.1 - - [24/Jan/2019 12:09:17] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40364)
Traceback (most recent call last):
  File "~/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "~/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "~/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "~/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "~/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "~/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "4_2_simple_http_server.py", line 29, in do_GET
    self.wfile.write("Hello from server!")
  File "~/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
127.0.0.1 - - [24/Jan/2019 12:09:17] "GET /favicon.ico HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 40366)
Traceback (most recent call last):
  File "~/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "~/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "~/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "~/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "~/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "~/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "4_2_simple_http_server.py", line 29, in do_GET
    self.wfile.write("Hello from server!")
  File "~/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```
It looks like this can be fixed by prefixing the string on line 29: 

```
line 29        self.wfile.write(b"Hello from server!")
```
Here's a good answer on why that works: https://stackoverflow.com/a/6269785

**Comment by githubce** [comment]
The code is updated.
