### ISSUE TITLE
Chapter 4 recipe 3 throws error

### ISSUE THREAD

**Issue by dnck** [PacktPublishing/Python-Network-Programming-Cookbook-Second-Edition#4]
The program, ```4_3_extract_cookie_information.py``` throws an error. Perhaps this is due to changes in how bitbucket.com handles requests on their login page. Setting the variables, LOGIN_URL and NORMAL_URL on line 19 and 20, to some relatively less sophisticated ip works fine. 

Here's the traceback:

```
Traceback (most recent call last):
  File "4_3_extract_cookie_information.py", line 58, in <module>
    extract_cookie_info()
  File "4_3_extract_cookie_information.py", line 43, in extract_cookie_info
    resp = opener.open(LOGIN_URL, login_data)
  File "~/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "~/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "~/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "~/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "~/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by githubce** [comment]
Thanks a lot for the suggestion.
